FROM eclipse-temurin:17-jdk-alpine

WORKDIR /app

# Installer Maven
RUN apk add --no-cache maven

# Copier pom.xml et télécharger les dépendances
COPY pom.xml .
RUN mvn dependency:go-offline -B

# Copier le code source
COPY src src

# Exposer le port
EXPOSE 8080

# Commande pour démarrer l'application
CMD ["mvn", "spring-boot:run"]