FROM eclipse-temurin:17-jdk-alpine

WORKDIR /app

# Copier les fichiers de build
COPY pom.xml .
COPY mvnw .
COPY .mvn .mvn

# Rendre le script exécutable
RUN chmod +x ./mvnw

# Installer les dépendances
RUN ./mvnw dependency:go-offline -B

# Copier le code source
COPY src ./src

EXPOSE 8080

# Commande de développement
CMD ["./mvnw", "spring-boot:run"]